"""user_id insteed created_by_user

Revision ID: 08555c7c1dcc
Revises: f079976e0d97
Create Date: 2023-01-23 18:56:27.747484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08555c7c1dcc'
down_revision = 'f079976e0d97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('vehicles_created_by_user_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vehicles', 'created_by_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('created_by_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_created_by_user_fkey', 'vehicles', 'users', ['created_by_user'], ['id'], ondelete='CASCADE')
    op.drop_column('vehicles', 'user_id')
    # ### end Alembic commands ###
