"""empty message

Revision ID: 31c1bae23723
Revises: 72c2d1e00233
Create Date: 2022-08-30 22:36:49.010021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c1bae23723'
down_revision = '72c2d1e00233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vehicles', ['num_plate'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    # ### end Alembic commands ###
