"""users table and FK in vehicles

Revision ID: cc44298b52de
Revises: 31c1bae23723
Create Date: 2022-09-10 15:22:50.741146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc44298b52de'
down_revision = '31c1bae23723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vehicles', sa.Column('created_by_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'users', ['created_by_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'created_by_user')
    op.drop_table('users')
    # ### end Alembic commands ###
