"""empty message

Revision ID: dd950aeb5da2
Revises: 474264e0e16e
Create Date: 2023-02-26 21:14:37.434891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd950aeb5da2'
down_revision = '474264e0e16e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None)
    # ### end Alembic commands ###
