"""vehicle brand is now nullable

Revision ID: vehicle_brand_nullable
Revises: missing_email
Create Date: 2022-09-10 22:12:57.937785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'vehicle_brand_nullable'
down_revision = 'missing_email'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
